# Generated by Django 3.2.4 on 2021-06-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceHistoryEpidemicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('date', models.CharField(max_length=5)),
                ('province', models.CharField(max_length=4)),
                ('confirm', models.IntegerField()),
                ('dead', models.IntegerField()),
                ('heal', models.IntegerField()),
                ('confirm_add', models.IntegerField()),
                ('newConfirm', models.IntegerField()),
                ('newHeal', models.IntegerField()),
                ('newDead', models.IntegerField()),
            ],
        ),
    ]
