# Generated by Django 3.2.4 on 2021-06-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_wuhanpopulationmigrationout'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeiBoCommentWordRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=5)),
                ('num', models.IntegerField()),
            ],
        ),
    ]
