# Generated by Django 3.2.4 on 2021-06-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_weibocommentwordrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_sum', models.IntegerField()),
                ('middle_sum', models.IntegerField()),
                ('negative_sum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmotionWordData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=5)),
                ('num', models.IntegerField()),
                ('kind', models.IntegerField()),
            ],
        ),
    ]
